version: '3.8'

services:
  api:
    build: .
    ports:
      - "8085:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload